# -*- coding: utf-8 -*-
"""Basketball_basic_Query.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgwtC6l8m68GppQ7DuyA8sUl6wyWB74M
"""

pip install rdflib

pip install SPARQLWrapper

import rdflib
from rdflib.namespace import RDF, RDFS
from rdflib.plugins.sparql import prepareQuery

# Define the namespaces used in the ontology
NAMESPACE = {
    'rdf': RDF,
    'rdfs': RDFS,
    'fa': rdflib.Namespace('http://www.semanticweb.org/natishamallick/ontologies/2023/basketballNM#')
}

# Load the populated ontology graph
g = rdflib.Graph()
g.parse('NM.owl')

# Define the name of the BasketballPlayer you want to retrieve the position for
BasketballPlayer_name = 'Ben Sullivan'

# Define the SPARQL query to retrieve the position of the named basketballPlayer
query = prepareQuery(
    '''
    SELECT ?height
    WHERE {
        ?BasketballPlayer rdf:type fa:BasketballPlayer .
        ?BasketballPlayer fa:name ?name .
        ?BasketballPlayer fa:height ?height .
        FILTER (regex(?name, "%s", "i"))
    }
    ''' % BasketballPlayer_name,
    initNs=NAMESPACE
)

# Execute the SPARQL query and print the result
for result in g.query(query):
    height = result.height
    print(f'{BasketballPlayer_name} has height {height}')





